#!/bin/bash

st=$(($(date +%s%N)/1000000))

OMPI_MCA_mpi_warn_on_fork=0
export OMPI_MCA_mpi_warn_on_fork

python $vivaldi_path/src/interactive_mode/main.py $@

end=$(($(date +%s%N)/1000000))
duration=$((end-st))

echo "Vivaldi execution time:" $duration "msec"
